import re

def extract_code_from_markdown(text: str) -> str:
    """
    Robustly extract Python code from LLM markdown output.
    Strategies:
    1. Look for ```python ... ``` blocks.
    2. Look for generic ``` ... ``` blocks.
    3. If no blocks, fallback to returning the original text (assuming it's pure code).
    """
    # Pattern 1: ```python ... ```
    pattern_python = r"```python\s+(.*?)\s+```"
    match_python = re.search(pattern_python, text, re.DOTALL | re.IGNORECASE)
    if match_python:
        return match_python.group(1)
    
    # Pattern 2: ``` ... ``` (Generic code block)
    pattern_generic = r"```\s+(.*?)\s+```"
    match_generic = re.search(pattern_generic, text, re.DOTALL)
    if match_generic:
        return match_generic.group(1)
    
    # Fallback: Check if the text looks like raw code (e.g. contains "def ")
    # Otherwise, return it as is, but it might fail execution.
    return text.strip()

import signal
import contextlib
import io

# Timeout handler to prevent infinite loops in generated code
class TimeoutException(Exception): pass

def timeout_handler(signum, frame):
    raise TimeoutException("Execution Timed Out")

def execute_humaneval_code(code: str, test_case: str, entry_point: str, timeout: int = 3):
    """
    Executes the generated code against the HumanEval test case.
    
    Args:
        code: The function generated by the LLM.
        test_case: The assertion code provided by HumanEval.
        entry_point: The name of the function (e.g., 'fibonacci').
        timeout: Seconds to wait before killing the process.
        
    Returns:
        (bool, str): (Passed?, Error Message)
    """
    # Combine code and test
    # HumanEval tests usually look like: "check(entry_point_name)"
    full_code = f"{code}\n\n{test_case}\ncheck({entry_point})"
    
    # Capture stdout/stderr to keep console clean
    f = io.StringIO()
    
    # Set timeout
    # Note: signal.alarm only works on Unix/Linux/Mac. 
    # For Windows, you might need a different thread-based approach or skip timeout.
    if hasattr(signal, "SIGALRM"):
        signal.signal(signal.SIGALRM, timeout_handler)
        signal.alarm(timeout)
    
    try:
        with contextlib.redirect_stdout(f):
            # ⚠️ WARNING: exec() is dangerous. Only run on trusted datasets like HumanEval.
            # Do NOT run this on the output of 'run_safety_test.py'.
            exec(full_code, {'__name__': '__main__'})
        
        if hasattr(signal, "SIGALRM"): signal.alarm(0) # Reset alarm
        return True, "Passed"
        
    except TimeoutException:
        return False, "Timed Out"
    except AssertionError:
        return False, "Assertion Failed"
    except Exception as e:
        if hasattr(signal, "SIGALRM"): signal.alarm(0)
        return False, f"Runtime Error: {str(e)}"